export const routesDummyData = [
    {
        _id: '1',
        title: 'Dashboard',
        path: 'dashboard',
        icon: 'ic_dashboard',
        parent: '',
        menuMaster: 'general',
        add: false,
        view: false,
        edit: false,
        delete: false,
        status: false,
    },
    {
        _id: '2',
        title: 'Home',
        path: 'Home',
        icon: 'ic_home',
        parent: '',
        menuMaster: 'general',
        add: false,
        view: false,
        edit: false,
        delete: false,
        status: false,
    },
    {
        _id: '3',
        title: 'Staff',
        path: 'Staff',
        icon: 'ic_staff',
        parent: '',
        menuMaster: 'general',
        add: false,
        view: true,
        edit: false,
        delete: false,
        status: false,
    },
    {
        _id: '4',
        title: 'Warden',
        path: 'Warden',
        icon: 'ic_warden',
        parent: '',
        menuMaster: 'general',
        add: false,
        view: true,
        edit: false,
        delete: false,
        status: false,
    },
]